-- Migration 0059: Replace universities table with Chatwoot custom-attribute list values.
-- uni_name matches Chatwoot labels exactly (including campus suffixes).

DELETE FROM universities;

INSERT INTO universities (uni_name, uni_shortname, district) VALUES
  ('Bahçeşehir Üniversitesi', 'Bahçeşehir Üniversitesi', NULL),
  ('Galatasaray Üniversitesi', 'Galatasaray Üniversitesi', NULL),
  ('Kadir Has Üniversitesi', 'Kadir Has Üniversitesi', NULL),
  ('Kent Üniversitesi - Taksim', 'Kent Üniversitesi', 'Taksim'),
  ('Kent Üniversitesi - Kağıthane', 'Kent Üniversitesi', 'Kağıthane'),
  ('İTÜ - Ayazağa', 'İTÜ', 'Ayazağa'),
  ('İTÜ - Maçka', 'İTÜ', 'Maçka'),
  ('YTÜ - Beşiktaş', 'YTÜ', 'Beşiktaş'),
  ('YTÜ - Davutpaşa', 'YTÜ', 'Davutpaşa'),
  ('Boğaziçi - Ana Kampüs', 'Boğaziçi', 'Ana Kampüs'),
  ('Boğaziçi - Anadolu Hisarı', 'Boğaziçi', 'Anadolu Hisarı'),
  ('Atlas Üniversitesi', 'Atlas Üniversitesi', NULL),
  ('MSGSÜ - Bomonti', 'MSGSÜ', 'Bomonti'),
  ('MSGSÜ - Beşiktaş', 'MSGSÜ', 'Beşiktaş'),
  ('Beykent Üniversitesi - Ayazağa', 'Beykent Üniversitesi', 'Ayazağa'),
  ('Beykent Üniversitesi - Taksim', 'Beykent Üniversitesi', 'Taksim'),
  ('Galata Üniversitesi', 'Galata Üniversitesi', NULL),
  ('Acıbadem Üniversitesi', 'Acıbadem Üniversitesi', NULL),
  ('Medipol Üniversitesi - Kuzey', 'Medipol Üniversitesi', 'Kuzey'),
  ('Medipol Üniversitesi - Güney', 'Medipol Üniversitesi', 'Güney'),
  ('Yeni Yüzyıl Üniversitesi', 'Yeni Yüzyıl Üniversitesi', NULL),
  ('İstinye Üniversitesi - Vadi', 'İstinye Üniversitesi', 'Vadi'),
  ('İstinye Üniversitesi - Cevizlibağ', 'İstinye Üniversitesi', 'Cevizlibağ'),
  ('Biruni Üniversitesi', 'Biruni Üniversitesi', NULL),
  ('Arel Üniversitesi - Cevizlibağ', 'Arel Üniversitesi', 'Cevizlibağ'),
  ('Marmara Üniversitesi - Göztepe', 'Marmara Üniversitesi', 'Göztepe'),
  ('Marmara Üniversitesi - Maltepe', 'Marmara Üniversitesi', 'Maltepe'),
  ('İstanbul Üniversitesi', 'İstanbul Üniversitesi', NULL),
  ('Üsküdar Üniversitesi', 'Üsküdar Üniversitesi', NULL),
  ('Medeniyet Üniversitesi - Kuzey', 'Medeniyet Üniversitesi', 'Kuzey'),
  ('Medeniyet Üniversitesi - Güney', 'Medeniyet Üniversitesi', 'Güney'),
  ('Bezmialem Vakıf Üniversitesi', 'Bezmialem Vakıf Üniversitesi', NULL),
  ('Demiroğlu Bilim Üniversitesi - Gayrettepe', 'Demiroğlu Bilim Üniversitesi', 'Gayrettepe'),
  ('Fenerbahçe Üniversitesi', 'Fenerbahçe Üniversitesi', NULL),
  ('Fatih Sultan Mehmet - Fatih', 'Fatih Sultan Mehmet', 'Fatih'),
  ('Fatih Sultan Mehmet - Beyoğlu', 'Fatih Sultan Mehmet', 'Beyoğlu'),
  ('Fatih Sultan Mehmet - Üsküdar', 'Fatih Sultan Mehmet', 'Üsküdar'),
  ('Haliç Üniversitesi', 'Haliç Üniversitesi', NULL),
  ('Işık Üniversitesi - Maslak', 'Işık Üniversitesi', 'Maslak'),
  ('29 Mayıs Üniversitesi', '29 Mayıs Üniversitesi', NULL),
  ('Bilgi Üniversitesi - Santralistanbul', 'Bilgi Üniversitesi', 'Santralistanbul'),
  ('Bilgi Üniversitesi - Dolapdere', 'Bilgi Üniversitesi', 'Dolapdere'),
  ('Bilgi Üniversitesi - Kuştepe', 'Bilgi Üniversitesi', 'Kuştepe'),
  ('Nişantaşı Üniversitesi - Maslak 1453', 'Nişantaşı Üniversitesi', 'Maslak 1453'),
  ('Nişantaşı Üniversitesi - Nişantaşı', 'Nişantaşı Üniversitesi', 'Nişantaşı'),
  ('Ticaret Üniversitesi - Küçükyalı', 'Ticaret Üniversitesi', 'Küçükyalı'),
  ('Ticaret Üniversitesi - Üsküdar', 'Ticaret Üniversitesi', 'Üsküdar'),
  ('Topkapı Üniversitesi - Merter', 'Topkapı Üniversitesi', 'Merter'),
  ('Topkapı Üniversitesi - Fatih', 'Topkapı Üniversitesi', 'Fatih'),
  ('MEF Üniversitesi - Maslak', 'MEF Üniversitesi', 'Maslak'),
  ('Yeditepe Üniversitesi', 'Yeditepe Üniversitesi', NULL),
  ('Kültür Üniversitesi', 'Kültür Üniversitesi', NULL),
  ('Maltepe Üniversitesi', 'Maltepe Üniversitesi', NULL),
  ('İstanbul Üniversitesi Cerrahpaşa', 'İstanbul Üniversitesi', 'Cerrahpaşa'),
  ('Doğuş Üniversitesi Çengelköy', 'Doğuş Üniversitesi', 'Çengelköy'),
  ('Doğuş Üniversitesi Dudullu', 'Doğuş Üniversitesi', 'Dudullu'),
  ('Gelişim Üniversitesi', 'Gelişim Üniversitesi', NULL),
  ('Esenyurt Üniversitesi', 'Esenyurt Üniversitesi', NULL),
  ('İstanbul Aydın Üniversitesi', 'İstanbul Aydın Üniversitesi', NULL),
  ('Arel Üniversitesi - Büyükçekmece', 'Arel Üniversitesi', 'Büyükçekmece'),
  ('Arel Üniversitesi - Sefaköy', 'Arel Üniversitesi', 'Sefaköy'),
  ('Bahçeşehir Üniversitesi - Future Campus', 'Bahçeşehir Üniversitesi', 'Future Campus'),
  ('Bahçeşehir Üniversitesi - Göztepe', 'Bahçeşehir Üniversitesi', 'Göztepe'),
  ('Koç Üniversitesi', 'Koç Üniversitesi', NULL),
  ('Sabancı Üniversitesi', 'Sabancı Üniversitesi', NULL),
  ('Beykoz Üniversitesi', 'Beykoz Üniversitesi', NULL),
  ('Özyeğin Üniversitesi', 'Özyeğin Üniversitesi', NULL),
  ('Okan Üniversitesi', 'Okan Üniversitesi', NULL),
  ('Demiroğlu Bilim Üniversitesi - Silivri', 'Demiroğlu Bilim Üniversitesi', 'Silivri'),
  ('Sağlık Bilimleri Üniversitesi', 'Sağlık Bilimleri Üniversitesi', NULL),
  ('Altınbaş Üniversitesi - Mahmutbey', 'Altınbaş Üniversitesi', 'Mahmutbey'),
  ('Altınbaş Üniversitesi - Esentepe', 'Altınbaş Üniversitesi', 'Esentepe'),
  ('Altınbaş Üniversitesi - Bakırköy', 'Altınbaş Üniversitesi', 'Bakırköy'),
  ('Işık Üniversitesi - Şile', 'Işık Üniversitesi', 'Şile'),
  ('İbn Haldun Üniversitesi', 'İbn Haldun Üniversitesi', NULL),
  ('İstanbul Galata Üniversitesi', 'İstanbul Galata Üniversitesi', NULL),
  ('İstanbul Rumeli Üniversitesi - Silivri', 'İstanbul Rumeli Üniversitesi', 'Silivri'),
  ('Piri Reis Üniversitesi', 'Piri Reis Üniversitesi', NULL),
  ('Şişli MYO', 'Şişli MYO', NULL),
  ('Ataşehir Adıgüzel MYO', 'Ataşehir Adıgüzel MYO', NULL),
  ('Sağlık ve Sosyal Bilimler MYO', 'Sağlık ve Sosyal Bilimler MYO', NULL);
